dist: xenial

os:
#    - osx
    - linux
#    - windows

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
        - BL_ADDON=fake_addon
    matrix:
        - BLENDER_VERSION="3.0"
        - BLENDER_VERSION="2.93"
        - BLENDER_VERSION="2.92"
        - BLENDER_VERSION="2.83"

language: python
python:
    - 3.8

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${BLENDER_CACHE}

addons:
    apt:
        packages:
            - blender

before_install:
    - mkdir -p ${BLENDER_CACHE}
    - ls ${BLENDER_CACHE}
    #- rm -rf ${BLENDER_CACHE}/*${BLENDER_VERSION}*
    - pip install -r ${TRAVIS_BUILD_DIR}/requirements.txt --upgrade
    - pip list

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd examples/testing-fake-addon/
    #- pip install -r requirements.txt
    - export PYTHONPATH=${TRAVIS_BUILD_DIR}
    - pip install -r ${PYTHONPATH}/blender_addon_tester/requirements.txt
    - python test_addon_blender.py ${BL_ADDON} ${BLENDER_VERSION}
    #- bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        on_success: change
        on_failure: always
